name: ğŸ§ª Integration Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    name: âš—ï¸ Application Tests
    uses: WGBH-MLA/.github/.github/workflows/pytest-with-postgres.yml@main
    secrets: inherit
    with:
      pdm_args: -G test,ci
      pytest_args: -n auto --nbmake -ra -s
      pg_db: chowda

  lint:
    name: ğŸ‘• Lint
    uses: WGBH-MLA/.github/.github/workflows/lint.yml@main

  black:
    name: ğŸ–¤ Black
    uses: WGBH-MLA/.github/.github/workflows/black.yml@main
