name: ğŸ§ª Integration Tests

on: [push, pull_request]

jobs:
  postgres:
    runs-on: ubuntu-latest
    # Docker Hub image
    container: postgres
    # Provide the password for postgres
    env:
      POSTGRES_PASSWORD: postgres

  tests:
    name: âš—ï¸ Application Tests
    uses: WGBH-MLA/.github/.github/workflows/pytest.yml@pdm
    secrets: inherit
    with:
      pdm_args: -G test,ci
      pytest_args: -n auto --nbmake
    needs: postgres

  lint:
    name: ğŸ‘• Lint
    uses: WGBH-MLA/.github/.github/workflows/lint.yml@main

  black:
    name: ğŸ–¤ Black
    uses: WGBH-MLA/.github/.github/workflows/black.yml@main
