name: ğŸ§ª Integration Tests

on: [push, pull_request]

jobs:
  tests:
    name: âš—ï¸ Application Tests
    uses: WGBH-MLA/.github/.github/workflows/pytest-with-postgres.yml@pytest-with-postgres
    secrets: inherit
    with:
      pdm_args: -G test,ci
      pytest_args: -n auto --nbmake
    environment:
      - DB_USER: postgres
      - DB_PASSWORD: postgres
      - DB_HOST: localhost
      - DB_PORT: 5432

  lint:
    name: ğŸ‘• Lint
    uses: WGBH-MLA/.github/.github/workflows/lint.yml@main

  black:
    name: ğŸ–¤ Black
    uses: WGBH-MLA/.github/.github/workflows/black.yml@main
